INSERT INTO car (model, image, carmaker, price, quantity) VALUES ('Fusca', '\images\defalut\default_img.png', 0, 10000.00, 50)
INSERT INTO car (model, image, carmaker, price, quantity) VALUES ('Gol', '\images\defalut\default_img.png', 4, 27000.00, 16)
INSERT INTO car (model, image, carmaker, price, quantity) VALUES ('Punto', '\images\defalut\default_img.png', 0, 34000.00, 23)
INSERT INTO car (model, image, carmaker, price, quantity) VALUES ('C3', '\images\defalut\default_img.png', 3, 45000.00, 6)
INSERT INTO car (model, image, carmaker, price, quantity) VALUES ('Mustang GT', '\images\defalut\default_img.png', 2, 10000.00, 2)